"""
Generate SHACL Turtle files from SHACLPlay Excel files.

This script takes the SHACLPlay Excel files generated by gen_shaclplay.py
and converts them to SHACL Turtle format using the xls2rdf tool.
"""

from pathlib import Path
import subprocess

# Configuration
SHACLPLAY_INPUT_DIR = Path("./outputs/shaclplay/")
SHACL_OUTPUT_BASE_DIR = Path("./outputs/shacl_shapes/")
XLS2RDF_JAR = Path("./inputs/shacls/xls2rdf-app-3.2.1-onejar.jar")

# Package configuration
# Set to package name (e.g., 'hri') to output files to './outputs/shacl_shapes/{package}/' with prefix '{package}-'
# Set to None for no package (output directly to './outputs/shacl_shapes/')
PACKAGE = 'hri'


def main():
    """Main conversion function."""
    print("=" * 80)
    print("SHACL Turtle Generator from SHACLPlay Excel")
    print("=" * 80)
    print()

    # Determine output directory and filename prefix based on package
    if PACKAGE:
        output_dir = SHACL_OUTPUT_BASE_DIR / PACKAGE
        file_prefix = f"{PACKAGE}-"
        print(f"Package: {PACKAGE}")
        print(f"Output directory: {output_dir}")
        print(f"File prefix: {file_prefix}")
    else:
        output_dir = SHACL_OUTPUT_BASE_DIR
        file_prefix = ""
        print(f"Output directory: {output_dir}")
        print("No package specified - files will not have a prefix")
    print()

    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)

    # Check if xls2rdf JAR exists
    if not XLS2RDF_JAR.exists():
        print(f"ERROR: xls2rdf JAR not found at {XLS2RDF_JAR}")
        print("Please ensure the JAR file is in the correct location.")
        return

    # Find all SHACLPlay Excel files
    excel_files = list(SHACLPLAY_INPUT_DIR.glob("SHACL-*.xlsx"))

    if not excel_files:
        print(f"No SHACLPlay Excel files found in {SHACLPLAY_INPUT_DIR}")
        print("Please run gen_shaclplay.py first.")
        return

    print(f"Found {len(excel_files)} SHACLPlay Excel files to convert")
    print()

    # Process each file
    for excel_file in excel_files:
        # Generate output filename (e.g., SHACL-dataset.xlsx -> dataset.ttl or hri-dataset.ttl)
        class_name = excel_file.stem.replace("SHACL-", "")
        output_file = output_dir / f"{file_prefix}{class_name}.ttl"

        print(f"Converting {excel_file.name}...")
        print(f"  Input: {excel_file}")
        print(f"  Output: {output_file}")

        try:
            # Run xls2rdf conversion
            # -i: input file
            # -o: output file
            # -sh: Skip hidden
            # -np: No postprocessing
            cmd = [
                "java",
                "-jar",
                str(XLS2RDF_JAR),
                "convert",
                "-i", str(excel_file),
                "-o", str(output_file),
                "-sh",
                "-np"
            ]

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True
            )

            print(f"  ✓ Successfully generated {output_file}")

            # Print any stdout/stderr for debugging
            if result.stdout:
                print(f"  Output: {result.stdout.strip()}")
            if result.stderr:
                print(f"  Warnings: {result.stderr.strip()}")

            print()

        except subprocess.CalledProcessError as e:
            print(f"  ✗ Error converting {excel_file.name}")
            print(f"  Return code: {e.returncode}")
            if e.stdout:
                print(f"  stdout: {e.stdout}")
            if e.stderr:
                print(f"  stderr: {e.stderr}")
            print()

        except Exception as e:
            print(f"  ✗ Unexpected error: {e}")
            import traceback
            traceback.print_exc()
            print()

    print("=" * 80)
    print("Conversion complete!")
    print(f"SHACL Turtle files written to {output_dir}")
    print("=" * 80)


if __name__ == "__main__":
    main()
