"""
Generate SHACL Turtle files from SHACLPlay Excel files.

This script takes the SHACLPlay Excel files generated by gen_shaclplay.py
and converts them to SHACL Turtle format using the xls2rdf tool.
"""

import traceback
from pathlib import Path
import subprocess
import pandas as pd

# Configuration
# SHACLPLAY_INPUT_DIR = Path("./outputs/shaclplay/eucaim")
SHACLPLAY_INPUT_DIR = Path("./outputs/shaclplay/hri")
SHACL_OUTPUT_BASE_DIR = Path("./outputs/shacl_shapes/")
XLS2RDF_JAR = Path("./inputs/shacls/xls2rdf-app-3.2.1-onejar.jar")


def extract_namespace_from_excel(excel_file: Path) -> str:
    """
    Extract namespace prefix from SHACLPlay Excel file.

    Reads the NodeShapes sheet and extracts the namespace from the NodeShape URI
    (e.g., "hri:DatasetShape" -> "hri")

    Args:
        excel_file: Path to the SHACLPlay Excel file

    Returns:
        Namespace prefix string
    """
    try:
        # Read NodeShapes sheet without headers
        df = pd.read_excel(excel_file, sheet_name='NodeShapes (classes)', header=None)

        # The NodeShape URI is in row 13, column 0 (e.g., "hri:DatasetShape")
        nodeshape_uri = df.iloc[13, 0]

        # Extract namespace prefix (part before the colon)
        if ':' in str(nodeshape_uri):
            namespace = nodeshape_uri.split(':')[0]
            return namespace
        else:
            raise ValueError(f"No namespace prefix found in NodeShape URI: {nodeshape_uri}")

    except Exception as e:
        print(f"Warning: Could not extract namespace from {excel_file.name}: {e}")
        print("Falling back to directory name")
        return SHACLPLAY_INPUT_DIR.name


def main():
    """Main conversion function."""
    print("=" * 80)
    print("SHACL Turtle Generator from SHACLPlay Excel")
    print("=" * 80)
    print()

    # Check if xls2rdf JAR exists
    if not XLS2RDF_JAR.exists():
        print(f"ERROR: xls2rdf JAR not found at {XLS2RDF_JAR}")
        print("Please ensure the JAR file is in the correct location.")
        return

    # Find all SHACLPlay Excel files
    excel_files = list(SHACLPLAY_INPUT_DIR.glob("SHACL-*.xlsx"))

    if not excel_files:
        print(f"No SHACLPlay Excel files found in {SHACLPLAY_INPUT_DIR}")
        print("Please run gen_shaclplay.py first.")
        return

    print(f"Found {len(excel_files)} SHACLPlay Excel files to convert")
    print()

    # Process each file
    for excel_file in excel_files:
        # Extract namespace from the Excel file
        namespace = extract_namespace_from_excel(excel_file)
        output_dir = SHACL_OUTPUT_BASE_DIR / namespace
        file_prefix = f"{namespace}-"

        print(f"Namespace: {namespace}")
        print(f"Output directory: {output_dir}")
        print(f"File prefix: {file_prefix}")
        print()

        # Create output directory
        output_dir.mkdir(parents=True, exist_ok=True)
        # Generate output filename (e.g., SHACL-dataset.xlsx -> dataset.ttl or hri-dataset.ttl)
        class_name = excel_file.stem.replace("SHACL-", "")
        output_file = output_dir / f"{file_prefix}{class_name}.ttl"

        print(f"Converting {excel_file.name}...")
        print(f"  Input: {excel_file}")
        print(f"  Output: {output_file}")

        try:
            # Run xls2rdf conversion
            # -i: input file
            # -o: output file
            # -sh: Skip hidden
            # -np: No postprocessing
            cmd = [
                "java",
                "-jar",
                str(XLS2RDF_JAR),
                "convert",
                "-i", str(excel_file),
                "-o", str(output_file),
                "-sh",
                "-np"
            ]

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True
            )

            print(f"  ✓ Successfully generated {output_file}")

            # Print any stdout/stderr for debugging
            if result.stdout:
                print(f"  Output: {result.stdout.strip()}")
            if result.stderr:
                print(f"  Warnings: {result.stderr.strip()}")

            print()

        except subprocess.CalledProcessError as e:
            print(f"  ✗ Error converting {excel_file.name}")
            print(f"  Return code: {e.returncode}")
            if e.stdout:
                print(f"  stdout: {e.stdout}")
            if e.stderr:
                print(f"  stderr: {e.stderr}")
            print()

        except Exception as e:
            print(f"  ✗ Unexpected error: {e}")
            traceback.print_exc()
            print()

    print("=" * 80)
    print("Conversion complete!")
    print(f"SHACL Turtle files written to {output_dir}")
    print("=" * 80)


if __name__ == "__main__":
    main()
